(define (problem LIGHTSOUTRBG)
    (:domain LIGHTSOUTRBG)
    (:objects x1 x2 x3 y1 y2 y3 - posicao)
    (:init
        (branco x1 y1)
        (azul x1 y2)
        (branco x1 y3)
        (azul x2 y1)
        (azul x2 y2)
        (azul x2 y3)
        (branco x3 y1)
        (azul x3 y2)
        (branco x3 y3)
    )
    (:goal
        (branco x1 y1)
        (branco x1 y2)
        (branco x1 y3)
        (branco x2 y1)
        (branco x2 y2)
        (branco x2 y3)
        (branco x3 y1)
        (branco x3 y2)
        (branco x3 y3)
    )
)