; Problem

(define
	(problem LIGHTSOUTRGB)
	(:domain LIGHTSOUTRGB)
	(:objects x0 x1 x2 x3 x4 x5 - line y0 y1 y2 y3 y4 - column)
	(:init
		(red x0 y0)
		(red x1 y0)
		(white x1 y1)
		(red x1 y2)
		(white x1 y3)
		(green x2 y0)
		(red x2 y1)
		(green x2 y2)
		(red x2 y3)
		(red x2 y4)
		(red x2 y5)
		(green x3 y0)
		(red x3 y1)
		(red x3 y2)
		(normal x0 y0)
		(normal x1 y0)
		(normal x1 y1)
		(normal x1 y2)
		(normal x1 y3)
		(normal x2 y0)
		(normal x2 y1)
		(normal x2 y2)
		(normal x2 y3)
		(normal x2 y4)
		(normal x2 y5)
		(normal x3 y0)
		(normal x3 y1)
		(normal x3 y2)
	)
	(:goal (forall (?w - line)(and
                (forall (?q - column)(and
                    (white ?w ?q)
                ))
            ))
	)
)